### ISSUE TITLE
install problem: installing in NUS HPC, but the GCC is old, and can not install the latest colossalai

### ISSUE THREAD

**Issue by Arsmart123** [hpcaitech/ColossalAI-Benchmark#9]
### 🐛 Describe the bug

I am installing the latest colossalai using the python setup.py install command, and the NUS HPC prompt some errors like: 
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
#error "You're running a too old version of GCC. We need GCC 5 or later."
![image](https://user-images.githubusercontent.com/65449458/156163208-69cb1cd8-6d50-4ea2-aca4-6f4d17d0e72d.png)

If I use pip install colossalai, another error happens!
![image](https://user-images.githubusercontent.com/65449458/156163409-55a5b828-fb6f-4f56-a3d2-9a157f5c8a12.png)
Well, pip install need Internet, and if I am using GPU in NUS, no internet can be accessed, so I have to use python setup.py install, but the GCC version is too old...

Lucky for me (maybe unlucky for other students using the server), I saved the old version's colossalai....

Thank you!!!

**Comment by FrankLeeeee** [comment]
Hi, we can't help with the GCC version as you have to build a higher version on your own. For the `pip install` issue, it seems that it cannot find the $CUDA_HOME variable. Can you make sure that you have CUDA in your path?

**Comment by Arsmart123** [comment]
> Hi, we can't help with the GCC version as you have to build a higher version on your own. For the `pip install` issue, it seems that it cannot find the $CUDA_HOME variable. Can you make sure that you have CUDA in your path?

oh...For NUS HPC, if I apply for GPU, I will have no access to the Internet. Anyway, seems I can not use the latest version on NUS HPC~

**Comment by Arsmart123** [comment]
![image](https://user-images.githubusercontent.com/65449458/156743795-26793917-bcc5-4692-a330-859121a89372.png)
I successfully upgrade my GCC version to 5.2 and still meet this error....Is it possible to provide some suggestions? Thank you!!

**Comment by Arsmart123** [comment]
I think...is it possible to make the installation not relavant to the CUDA and torch?Just like installing pytorch, I can install GPU version even I do not have a GPU for now....

**Comment by Arsmart123** [comment]
I uninstall my pytorch1.10 and install a 1.9 version and also use GCC6 (but not like mentioned in the error GCC5). Maybe this colossalai is bound to pytorch1.9 and below?

**Comment by Arsmart123** [comment]
And using torch1.9 and GCC6 it compiles longer than before colossalai version, about, 5-10 min?

**Comment by Arsmart123** [comment]
![image](https://user-images.githubusercontent.com/65449458/156765645-789a4811-6747-458c-9580-663cce8514f7.png)
I failed on NSCC now...NSCC has only cuda10.1 and can not be upgraded, so I have to install pytorch1.8 (up to 1.8.....can not install 1.9 or later) And I meet this problem using pip install colossalai
(By the way, I can not find method to solve that on google...seems no other people met this....)
Thanks!

**Comment by Arsmart123** [comment]
Although NSCC has only cuda10.1, but seems torch1.9+cuda10.2 is ok, and this time my installation of colossalai is very easy. So current version's restriction seems to be: GCC6 (my previous try of GCC5 is not ok), + torch1.9 (1.8 and 1.10 does not work)

**Comment by Arsmart123** [comment]
Strangely, I install colossalai again today on cuda10.1+torch1.8 on NSCC's device and it worked! Maybe no more help is needed~

**Comment by Arsmart123** [comment]
> Strangely, I install colossalai again today on cuda10.1+torch1.8 on NSCC's device and it worked! Maybe no more help is needed~

**Details about how I install this verison**
Note that my device only support cuda version up to 10.1, and the driver can not be upgrated...
I tried torch1.8+cuda10.1 and it failed, so I install torch1.9+cuda10.2, installation is ok, but maybe can not run. And I install colossalai, success! (My later guess is, just like cuda11 will have cudnn inside, but cuda10 not, maybe torch1.9+cuda10.2 has something inside but torch1.8+cuda10.1 don't) But when I use colossalai, it shows no GPU found! So I again uninstall torch1.9+cuda10.2 and install torch1.8+cuda10.1. And this time, GPU can be found and colossalai can run!

**Comment by FrankLeeeee** [comment]
Great, glad to hear that!
